config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :lamdba, only: %i[index create new show]
  require 'sidekiq/web'
mount Sidekiq::Web => '/sidekiq'
  post '/welcome', to: 'lamdba#welcome'
  post '/deliveroo', to: 'lamdba#welcome'
  root to: 'lamdba#new'
  post '/v1/orders/:order_id/sync_status',  to: 'lamdba#sync_status'
  get '/v1/orders/111/prep_stage', to: 'lamdba#prep_stage'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  has_many :contact_phones
  has_many :contact_addresses
end

app/models/contact_address.rb
class ContactAddress < ApplicationRecord
end

app/models/contact_phone.rb
class ContactPhone < ApplicationRecord
end

app/models/lamdba.rb
class Lamdba < ApplicationRecord
  require 'rest-client'
  def details(params)
    # RestClient.post ENV['url'], key: 1
    @lamdba = Lamdba.new
    @lamdba.key = params['key'].to_i
    @lamdba.save
    @response = RestClient::Request.execute(method: :post, url: ENV['url'],
                                            payload: {
                                              key: params['key'].to_i,
                                              id: @lamdba.id
                                            }.to_json,
                                            timeout: 10)

    response = JSON.parse(@response.body)
    # @lamdba = Lamdba.new
    # @lamdba.key = response['key'].to_i
    # @lamdba.square_value = response['square_value'].to_i
    # @lamdba.save
    response['key'].to_i
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lamdba_controller.rb
# LamdbaController to communicate with lamdba function
class LamdbaController < ApplicationController
  skip_before_action :verify_authenticity_token
  require 'openssl'
  def create
    puts params
    id = Lamdba.new.details(params['lamdba'])
    redirect_to lamdba_path(id)
  end

  def new
    puts "a"
    @lamdba = Lamdba.new
  end

  def show
    @lamdba = Lamdba.find(params[:id])
  end

  def index
    @lambda = Lamdba.all
  end

  def welcome
    Rails.logger.info params
    Rails.logger.info params.class
    Rails.logger.info params["invoice_id"]
    Rails.logger.info params["invoice_id"].class
    Rails.logger.info params[:invoice_id].class
    # @api = ApiIntegration.get_api_integration_instance(request)
    # status = @api.authenticate(request)
    # res = RestClient::Request.execute(method: :post,
    #                                   url: "https://4edi1hqmul.execute-api.us-east-2.amazonaws.com/sync_status_new/orderid/136508448508-5729",
    #                                   user: 'SAPAAD_PTE_LTD_Test--0075e1ef-4fa4-46b5-8ee3-bb1cc243bb3f',
    #                                   password: '42c11fb4-d895-4529-9c3f-7de6332ef9a9',
    #                                   payload: {
    #                                     "occurred_at": Time.now,
    #                                     "status": 'failed',
    #                                     "reason": 'invalid_total_price',
    #                                     "notes": ''
    #                                   })
    # Rails.logger.info status
    render json: { msg: 'hi' }
  end
  def sync_status
    Rails.logger.info request.raw_post
    render json: { order_id: params[:order_id] }
  end
  def prep_stage

    IpmListenerWorker.perform_in(5.seconds, {a:1})
    # res = RestClient::Request.execute(method: :post,
    #                                   url: "https://4edi1hqmul.execute-api.us-east-2.amazonaws.com/sync_status2/prep-stage/771504902908-5729",
    #                                   user: 'SAPAAD_PTE_LTD_Test--0075e1ef-4fa4-46b5-8ee3-bb1cc243bb3f',
    #                                   password: '42c11fb4-d895-4529-9c3f-7de6332ef9a9',
    #                                   payload: {
    #                                     "occurred_at": Time.now.strftime('%FT%TZ'),
    #                                     "stage": 'ready_for_collection'
    #                                   })
    #
    # puts res.code.inspect
    # render json: res.body.to_json
    render json: { a: 1}
  rescue
    render json: {}.to_json
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lamdba_helper.rb
module LamdbaHelper
end

app/views/lamdba/index.html.erb
<% @lambda.each do |lambda| %>
  <div class="" style="border:1px solid black;">
    <div>
      <div style="float:left;">
        <%=label_tag('key') %>:
      </div>
      <div class="">
        <%= lambda.key %>
      </div>
    </div>
    <div>
      <div style="float:left;">
        <%= label_tag('square') %>:
      </div>
      <div class="">
        <%= lambda.square_value %>
      </div>
    </div>
  </div>
  <br>
<% end %>

app/views/lamdba/new.html.erb
<%= form_with scope: :lamdba,url: lamdba_index_path, local: true do |form| %>
  <p>
    <%= form.label :key %><br>
    <%= form.text_field :key %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/lamdba/show.html.erb
<div>
  <div class="">
  <%=label_tag('key') %>:
  </div>
  <div class="">
    <%= @lamdba.key %>
  </div>
</div>
<div>
  <div class="">
    <%= label_tag('square') %>:
  </div>
  <div class="">
    <%= @lamdba.square_value %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LamdbaPoc</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>